name: Deployment
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Add Composer auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' | base64 -d > $GITHUB_WORKSPACE/auth.json

      - name: Install Shopware CLI
        uses: shopware/shopware-cli-action@v1

      - name: Build
        run: shopware-cli project ci .

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy staging
          private-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}