name: Deployment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Environment for Deployment


jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set personal access token for packages.shopware.com
        run: composer config bearer.packages.shopware.com "${{ secrets.SHOPWARE_PACKAGES_TOKEN }}"

      - name: Determine composer cache directory
        id: composer
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Load composer cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.composer.outputs.dir }}
          key: composer-${{ hashFiles('./composer.lock') }}

      - name: Install Shopware CLI
        uses: shopware/shopware-cli-action@v1

      - name: Build
        run: shopware-cli project ci . --with-dev-dependencies

      - name: Save composer cache
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.composer.outputs.dir }}
          key: composer-${{ hashFiles('./composer.lock') }}

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy ${{ inputs.environment }}
          private-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
